namespace _71695_2_4;

class JS_71695_Program
{
    static void Main(string[] args)
    {
        // string input = "LATA_OSA_KOŁO_NOSA_LATA_MUCHA_KOŁO_UCHA_LATA_BĄK_KOŁO_RĄK_LATA_OSA_KOŁO_NOSA_LATA_MUCHA_KOŁO_UCHA_LATA_BĄK_KOŁO_RĄK_LATA_OSA_KOŁO_NOSA_LATA_MUCHA_KOŁO_UCHA_LATA_BĄK_KOŁO_RĄK";
        // string input = "DBCDDCBBBCDBADBADACBCABACBACDCBCACDACADDBAAADBDCBDDDABACBCCAAACBCDBCBDADDBBBBCCBDDDBBAADDCDCCDADBDCDCCACADCDCAADDCDBAAABBACCDBDABBDCDBCCBCADDDDACCCCCBCBADDCDDCDBBCDCCBDCDBDABDBBDAABBAACACABDACAAADACAABDBCAABADCCADDBCACACBAACA";
        JS_71695_UserInteraction.JS_71695_RunProgram();
    }
}